---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --recursive --remote

  - name: build
    image: mangoh/mangoh_build:yellow-wp77xx_0.2.3
    commands:
      - echo "Echo"
      - make

trigger:
  event:
    include:
      - pull_request
